name: me_chat
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # Icons and UI components
  cupertino_icons: ^1.0.8

  # Device preview for responsive testing
  device_preview_plus: ^2.2.6
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  cloud_firestore: ^5.6.6
  supabase_flutter: ^2.8.4
  http: ^1.3.0
  file_picker: ^10.1.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  emoji_picker_flutter: ^4.3.0
  firebase_messaging: ^15.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended linting rules
  flutter_lints: ^5.0.0

  # Package for generating launcher icons
  flutter_launcher_icons: ^0.14.3

flutter_icons: # ✅ Correct key for launcher icon config
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # Fonts section (Add if you have custom fonts)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700
