// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBomnKiuhGz3f8U1R3PCN26P7b1bC080tc',
    appId: '1:34589953348:android:1133e493a09f67dff85b11',
    messagingSenderId: '34589953348',
    projectId: 'mechat-759d0',
    storageBucket: 'mechat-759d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0I9D5Icqn1J9nhimPvq5edfHEQ4zaSVI',
    appId: '1:34589953348:ios:a5408f462ec00848f85b11',
    messagingSenderId: '34589953348',
    projectId: 'mechat-759d0',
    storageBucket: 'mechat-759d0.firebasestorage.app',
    androidClientId: '34589953348-6pump0vls8t1032avmt3j198ojqf2j3t.apps.googleusercontent.com',
    iosClientId: '34589953348-c0rma8ck9ls9j7b9bo8tmrp3mbkvqacb.apps.googleusercontent.com',
    iosBundleId: 'com.example.meChat',
  );

}